apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelinerun-pvc2
spec:
  storageClassName: skills-network-learner
  resources:
    requests:
      storage:  1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
